apiVersion: v1
kind: Service
metadata:
  name: {{ include "envoy-grpc-test.fullname" . }}-server
  labels:
    helm.sh/chart: {{ include "envoy-grpc-test.chart" . }}
    app.kubernetes.io/name: {{ include "envoy-grpc-test.name" . }}-server
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: grpc-port
      protocol: TCP
      name: grpc-port
  selector:
    app.kubernetes.io/name: grpc-server
    app.kubernetes.io/instance: {{ .Release.Name }}
