apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grpc-server
  labels:
    {{- include "envoy-grpc-test.labels" . | nindent 4 }}
spec:
  serviceName: grpc-server
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: grpc-server
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grpc-server
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-server
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.server.image.repository }}:{{ .Chart.AppVersion }}"
          command: ["python"]
          args: ["/messenger/server.py"]
          ports:
            - name: grpc-port
              containerPort: 50505
              protocol: TCP
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}
