apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "envoy-grpc-test.fullname" . }}
  labels:
    {{- include "envoy-grpc-test.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "envoy-grpc-test.fullname" . }}-server
  replicas: {{ .Values.server.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "envoy-grpc-test.name" . }}-server
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "envoy-grpc-test.name" . }}-server
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-client
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.server.image.repository }}:{{ .Chart.AppVersion }}"
          command: ["python"]
          args: ["/messenger/server.py"]
          ports:
            - containerPort: 50505
              name: grpc-port
          imagePullPolicy: {{ .Values.server.image.pullPolicy }}

