apiVersion: v2
appVersion: 0.0.1
dependencies:
- alias: nalkinscloud-db
  condition: mariadb.enabled
  name: mariadb
  repository: https://charts.bitnami.com/bitnami
  tags:
  - e2e-test
  version: 9.1.4
- name: vault
  repository: https://helm.releases.hashicorp.com
  version: 0.8.0
  condition: vault.enabled
  tags:
    - e2e-test
description: Open source IOT framwork
home: https://www.nalkins.cloud
icon: null
keywords:
- nalkinscloud
- iot
- django
maintainers:
- email: levinsonarie@gmail.com
  name: Arie Lev
  url: https://www.nalkins.cloud
name: nalkinscloud
sources:
- https://github.com/ArieLevs/NalkinsCloud
version: 0.1.1
