# Default values for airflow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  replicaCount: 3
  image:
    privateRepo: true
    repository: docker.nalkins.cloud/nalkinscloud/nalkinscloud-django-backend
    tag: stable
    imagePullPolicy: IfNotPresent
  env:
    environment: alpha
    backend_domain: https://alpha.api.nalkins.cloud
    frontend_domain: https://alpha.nalkins.cloud
    email_host: smtp.gmail.com
    email_port: 587
    static_url: https://arielevs.github.io/
    # allowed_hosts passed as as string separated by ','
    allowed_hosts: "10.*"
    graylog_host: graylog.nalkins.cloud
    graylog_port: 12201

vaultAgent:
  enabled: false
  vaultRoleName: kube-agent-nalkinscloud-django-backend

dependantServices:
  - name: init-database
    image: busybox
    command: ['sh', '-c', 'env; until nc -z ${db_host} ${db_port} ; do echo waiting for database; sleep 2; done;']
    env:
      - name: db_host
        value: "alpha.centraldb.nalkins.cloud"
      - name: db_port
        value: "3306"

secrets:
  # If blank, random 50 char secret created
  ## NOTE - If using Argo CD this value must ve set or the app will always be in 'OutOfSync' state
  django_secret_key:

  docker:
    dockerSecretName: nalkinscloud-nexus-docker
    registry: docker.nalkins.cloud
    username: admin
    password: admin
  database:
    username: django
    password: django
  email:
    username: admin
    password: admin
  google:
    client_id: google_client_id
    client_secret: google_client_secret
  github:
    client_id: github_client_id
    client_secret: github_client_secret

configmap:
  databaseVars:
    # Key also used as env name inside project
    db_name: django
    db_host: alpha.centraldb.nalkins.cloud

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/ssl-redirect: true
    kubernetes.io/tls-acme: true
    certmanager.k8s.io/acme-dns01-provider: cf-dns
    certmanager.k8s.io/acme-challenge-type: dns01
    certmanager.k8s.io/cluster-issuer: letsencrypt-production
  path: /
  hosts:
    - alpha.api.nalkins.cloud
  tls:
    - secretName: nalkinscloud-api-tls
      hosts:
        - alpha.api.nalkins.cloud

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
