
tags:
  e2e-test: false

# values for the 'mariadb' subchart
nalkinscloud-db:
  enabled: false
  auth:
    rootPassword: "administrator"
    # creating db, username and password on first run
    database: django
    username: django
    password: django
  primary:
    persistence:
      enabled: false

vault:
  enabled: false
  injector:
    namespaceSelector:
      matchLabels:
        # update using --set below value so injector will have its webhook on a single namespace (ci use only)
        vault-injector: "random-namespace"
  server:
    dataStorage:
      enabled: false
    dev:
      enabled: true

deployment:
  ## Add annotations on pod level
  annotations:
    ## Annotations docs here: https://www.vaultproject.io/docs/platform/k8s/injector/annotations/
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "nalkinscloud-api"
    vault.hashicorp.com/agent-inject-secret-django-db-values: "secret/nalkinscloud-api/backend/database"
    vault.hashicorp.com/agent-inject-secret-django-config: "secret/nalkinscloud-api/backend/django"
    vault.hashicorp.com/agent-inject-status: "update"

    ## This should map to the same unique value provided in vault.hashicorp.com/agent-inject-secret-X
    ## Deployment template example can be found here:
    ## https://www.vaultproject.io/docs/platform/k8s/injector/examples/#deployments-statefulsets-etc
    vault.hashicorp.com/agent-inject-template-django-db-values: |
      {{- with secret "secret/nalkinscloud-api/backend/database" -}}
      db_host: {{ .Data.data.db_host }}
      db_name: {{ .Data.data.db_name }}
      db_port: {{ .Data.data.db_port }}
      username: {{ .Data.data.username }}
      password: {{ .Data.data.password }}
      {{- end -}}
    vault.hashicorp.com/agent-inject-template-django-config: |
      {{- with secret "secret/nalkinscloud-api/backend/django" -}}
      django_secret: {{ .Data.data.django_secret }}
      {{- end -}}

  replicaCount: 1
  image:
    privateRepo: true
    repository: docker.nalkins.cloud/nalkinscloud/nalkinscloud-django-backend
    tag: 0.0.46
    imagePullPolicy: IfNotPresent
  env:
    environment: alpha
    backend_domain: https://alpha.api.nalkins.cloud
    frontend_domain: https://alpha.nalkins.cloud
    email_host: smtp.gmail.com
    email_port: 587
    static_url: https://nalkins.cloud/
    # allowed_hosts passed as as string separated by ','
    allowed_hosts: "10.*"
    graylog_host: graylog.nalkins.cloud
    graylog_port: 12201

vaultAgent:
  enabled: false
  vaultRoleName: kube-agent-nalkinscloud-django-backend

dependantServices:
  - name: init-database
    image: busybox
    command: ['sh', '-c', 'env; until nc -z ${db_host} ${db_port} ; do echo waiting for database; sleep 2; done;']
    env:
      - name: db_host
        value: "nalkinscloud-api-nalkinscloud-db.e2etest.svc.cluster.local"
      - name: db_port
        value: "3306"

secrets:
  # If blank, random 50 char secret created
  ## NOTE - If using Argo CD this value must ve set or the app will always be in 'OutOfSync' state
  django_secret_key:

  docker:
    dockerSecretName: nalkinscloud-nexus-docker
    registry: docker.nalkins.cloud
    username: admin
    password: admin
  database:
    username: django
    password: django
  email:
    username: admin
    password: admin
  google:
    client_id: google_client_id
    client_secret: google_client_secret
  github:
    client_id: github_client_id
    client_secret: github_client_secret

configmap:
  databaseVars:
    # Key also used as env name inside project
    db_name: django
    db_host: nalkinscloud-api-nalkinscloud-db.e2etest.svc.cluster.local

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/ssl-redirect: true
    kubernetes.io/tls-acme: true
    cert-manager.io/cluster-issuer: letsencrypt-production
  path: /
  hosts:
    - api.alpha.nalkins.cloud
  tls:
    - secretName: nalkinscloud-api-tls
      hosts:
        - api.alpha.nalkins.cloud

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
