
deployment:
  ## Add annotations on pod level
  annotations:
    ## Annotations docs here: https://www.vaultproject.io/docs/platform/k8s/injector/annotations/
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "nalkinscloud-api"
    vault.hashicorp.com/agent-inject-secret-django-db-values: "secret/nalkinscloud-api/backend/database"
    vault.hashicorp.com/agent-inject-secret-django-config: "secret/nalkinscloud-api/backend/django"
    vault.hashicorp.com/agent-inject-status: "update"

    ## This should map to the same unique value provided in vault.hashicorp.com/agent-inject-secret-X
    ## Deployment template example can be found here:
    ## https://www.vaultproject.io/docs/platform/k8s/injector/examples/#deployments-statefulsets-etc
    vault.hashicorp.com/agent-inject-template-django-db-values: |
      {{- with secret "secret/nalkinscloud-api/backend/database" -}}
      db_host: {{ .Data.data.db_host }}
      db_name: {{ .Data.data.db_name }}
      db_port: {{ .Data.data.db_port }}
      username: {{ .Data.data.username }}
      password: {{ .Data.data.password }}
      {{- end -}}
    vault.hashicorp.com/agent-inject-template-django-config: |
      {{- with secret "secret/nalkinscloud-api/backend/django" -}}
      django_secret: {{ .Data.data.django_secret }}
      {{- end -}}

  replicaCount: 1
  image:
    privateRepo: true
    repository: docker.nalkins.cloud/nalkinscloud/nalkinscloud-django-backend
    tag: 0.0.46
  env:
    environment: alpha
    backend_domain: https://alpha.api.nalkins.cloud
    frontend_domain: https://alpha.nalkins.cloud
    # allowed_hosts passed as as string separated by ','
    allowed_hosts: "10.*"
    graylog_host: graylog.nalkins.cloud

configmap:
  databaseVars:
    # Key also used as env name inside project
    db_host: centraldb.alpha.nalkins.cloud

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/ssl-redirect: true
    kubernetes.io/tls-acme: true
    cert-manager.io/cluster-issuer: letsencrypt-production
  hosts:
    - api.alpha.nalkins.cloud
  tls:
    - secretName: nalkinscloud-api-tls
      hosts:
        - api.alpha.nalkins.cloud
