# Default values for airflow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  ## Add annotations on pod level
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "nalkinscloud-resume"
    vault.hashicorp.com/agent-inject-secret-credentials.txt: "secret/nalkinscloud-resume/backend/django"

  replicaCount: 2
  image:
    privateRepo: true
    repository: docker.nalkins.cloud/nalkinscloud-resume/nalkinscloud-resume
    tag: 0.0.23
    imagePullPolicy: IfNotPresent
  env:
    environment: alpha
    backend_domain: https://alpha.resume.nalkins.cloud
    frontend_domain: https://alpha.resume.nalkins.cloud
    email_host: smtp.gmail.com
    email_port: 587
    static_url: https://nalkins.cloud/
    allowed_hosts: "alpha.resume.nalkins.cloud,10.*"

vaultAgent:
  enabled: false
  vaultRoleName: kube-agent-nalkinscloud-resume

dependantServices:
  - name: init-database
    image: busybox
    command: ['sh', '-c', 'env; until nc -z ${db_host} ${db_port} ; do echo waiting for database; sleep 2; done;']
    env:
      - name: db_host
        value: "alpha.centraldb.nalkins.cloud"
      - name: db_port
        value: "3306"

secrets:
  # If blank, random 50 char secret created
  ## NOTE - If using Argo CD this value must ve set or the app will always be in 'OutOfSync' state
  django_secret_key:

  docker:
    dockerSecretName: nalkinscloud-nexus-docker
    registry: docker.nalkins.cloud
    username: admin
    password: admin
  database:
    username: django
    password: django
  email:
    username: admin
    password: admin

configmap:
  databaseVars:
    # Key also used as env name inside project
    db_name: django
    db_host: alpha.centraldb.nalkins.cloud

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/ssl-redirect: true
    kubernetes.io/tls-acme: true
    cert-manager.io/cluster-issuer: letsencrypt-production
  path: /
  hosts:
    - alpha.resume.nalkins.cloud
  tls:
    - secretName: nalkinscloud-resume-tls
      hosts:
        - alpha.resume.nalkins.cloud

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
