apiVersion: v1
appVersion: 0.0.1
description: Open source IOT framwork
engine: gotpl
home: https://www.nalkins.cloud
icon: null
keywords:
- nalkinscloud
- iot
- django
maintainers:
- email: levinsonarie@gmail.com
  name: Arie Lev
  url: https://www.nalkins.cloud
name: nalkinscloud-api
sources:
- https://github.com/ArieLevs/NalkinsCloud
version: 0.0.4
