# Default values for airflow.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  replicaCount: 1
  image:
    privateRepo: true
    repository: docker.nalkins.cloud/nalkinscloud/nalkinscloud-django
    tag: latest
    imagePullPolicy: Always
  env:
    databseUsernameKey: db_user
    databsePasswordKey: db_pass

environment: alpha

nginx:
  replicaCount: 1
  image:
    privateRepo: false
    repository: nginx
    tag: alpine
    imagePullPolicy: IfNotPresent
  configs:
    staticRoot: /static/
    serverName: nalkins.cloud.localhost

secrets:
  docker:
    dockerSecretName: nalkinscloud-nexus-docker
    registry: docker.nalkins.cloud
    username:
    password:
  database:
    databaseSecretName: nalkinscloud-api-database
    username:
    password:

configmap:
  databaseVars:
    db_name: django
    db_user: django
    db_host: centraldb.nalkins.cloud

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  ingressServiceName: nalkinscloud-api-nginx
  annotations:
    kubernetes.io/ingress.class: traefik
  path: /
  hosts:
    - nalkins.cloud.localhost
  #tls:
  #  - secretName: nalkins-cloud-tls
  #    hosts:
  #      - alpha.nalkins.cloud

persistent:
  enabled: true

  capacity:
    storage: 50Gi
  nfs:
    enabled: false
    server:
    path:
  local:
    enabled: true

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
