{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sms-verifier-backend.serviceAccountName" . }}
  labels:
{{ include "sms-verifier-backend.labels" . | nindent 4 }}
{{- end -}}
