# Default values for mosquitto.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: arielev/mosquitto
  tag: 1.5.5
  pullPolicy: IfNotPresent
  imagePullSecret: {}
  ##  dockerRegistry: docker.io
  ##  dockerUsername:
  ##  dockerPassword:

nameOverride: ""
fullnameOverride: ""

dependantServices: {}
  ## Specify dependant container here as example below
  ##- name: init-mysql
  ##  image: busybox
  ##  command: ['sh', '-c', 'until nc -z mysql.mysql.svc.cluster.local:3306 ; do echo waiting for mysql; sleep 2; done;']

config:
  authPlug:
    # set mysql backend values
    enabled: true
    dbHost: centraldb.alpha.nalkins.cloud
    dbPort: 3306
    dbName: django
    dbUser: django
    dbPass: django
  webSockets:
    enabled: false
    port: 9090
  addtionalConfigs: ""
    ## add additional configs from https://mosquitto.org/man/mosquitto-conf-5.html
    ## for example
    # |-
    #allow_anonymous true
    #
    #connection_messages true
    #log_timestamp true
    #log_type all
    #log_dest stdout

tls:
  enabled: false
  # possible values are tlsv1.3, tlsv1.2 and tlsv1.1
  tlsVersion: tlsv1.2
  certificates:
   ca: |-
     -----BEGIN CERTIFICATE-----
     ...
     -----END CERTIFICATE-----
   cert: |-
     -----BEGIN CERTIFICATE-----
     ...
     -----END CERTIFICATE-----
   key: |-
     -----BEGIN RSA PRIVATE KEY-----
     ...
     -----END RSA PRIVATE KEY-----

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 2Gi
  storageClass: standard

service:
  type: ClusterIP
  mqttPort: 1883
  mqttTLSPort: 8883
  websocketPort: 9090

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
