{{- if .Values.ingress.enabled -}}
{{- $fullName := include "nalkinscloud-api.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $ingressPort := .Values.service.port -}}
{{- $ingressServiceName := .Values.ingress.ingressServiceName -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "nalkinscloud-api.name" . }}
    chart: {{ template "nalkinscloud-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
        - path: {{ $ingressPath }}
          backend:
            serviceName: {{ $ingressServiceName }}
            servicePort: {{ $ingressPort }}
  {{- end }}
{{- end }}
