{{- $fullName := include "nalkinscloud-api.fullname" . -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $fullName }}-pv
  labels:
    app: {{ template "nalkinscloud-api.name" . }}
    chart: {{ template "nalkinscloud-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    pv.beta.kubernetes.io/gid: "0"
spec:
  capacity:
    storage: {{ .Values.persistent.capacity.storage }}
  accessModes:
    - ReadOnlyMany
  # indicates that the volume will be preserved after the pods accessing it terminates
  persistentVolumeReclaimPolicy: Retain
#  claimRef:
#    namespace: nalkinscloud-api
#    name: nalkinscloud-api
  nfs:
    path: {{ .Values.persistent.nfs.path }}
    server: {{ .Values.persistent.nfs.server }}
    readOnly: true