{{- $fullName := include "nalkinscloud-api.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "nalkinscloud-api.name" . }}
    chart: {{ template "nalkinscloud-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ $fullName }}
  ports:
  - name: nalkinscloud-api
    port: {{ .Values.service.port }}
    targetPort: 8000