apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.docker.dockerSecretName }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
---
apiVersion: v1
kind: Secret
metadata:
   name: {{ .Values.secrets.database.databaseSecretName }}
type: Opaque
data:
  db_user: {{ .Values.secrets.database.username | b64enc | quote }}
  db_pass: {{ .Values.secrets.database.password | b64enc | quote }}