{{- $fullName := include "nalkinscloud.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
{{ include "nalkinscloud.labels" . | indent 4 }}
spec:
  # externalTrafficPolicy: Local
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "nalkinscloud.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - name: nalkinscloud
    port: {{ .Values.service.port }}
    targetPort: 8000
    protocol: TCP
