{{- $fullName := include "nalkinscloud.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    upstream backend{
        server {{ $fullName }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.port }};
    }

    server {
        listen       80;
        #listen       443 ssl;
        server_name {{ .Values.nginx.configs.serverName }};

        error_log /dev/stdout debug;

        #ssl_certificate     /etc/nginx/pki/server.crt;
        #ssl_certificate_key /etc/nginx/pki/server.key;

        location = /favicon.ico { access_log off; log_not_found off; }

        location /static/ {
            autoindex on;
            alias {{ .Values.nginx.configs.staticRoot }};
        }

        location / {
            autoindex on;
            try_files $uri @proxy;
        }

        location @proxy {
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_X_forwarded_for;
            proxy_set_header Host $host;

            proxy_pass http://backend;

        }
    }
  server.conf: |
    user  nginx;
    worker_processes  2;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;


    events {
        worker_connections  1024;
    }


    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;

        include /etc/nginx/conf.d/*.conf;

        send_timeout 2;
    }