{{- $fullName := include "nalkinscloud.fullname" . -}}
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: {{ .Values.secrets.docker.dockerSecretName }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  backendType: vault
  vaultMountPoint: nalkinscloud-alpha-external-secrets
  vaultRole: kubernetes-external-secrets
  kvVersion: 2
  template:
    type: kubernetes.io/dockerconfigjson
  data:
    - name: .dockerconfigjson
      key: secret/data/nexus/docker
      property: dockerconfigjson
---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: {{ $fullName }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  backendType: vault
  vaultMountPoint: nalkinscloud-alpha-external-secrets
  vaultRole: kubernetes-external-secrets
  kvVersion: 2
  data:
    - name: django_secret_key
      key: secret/data/nalkinscloud-resume/backend/django
      property: db_user
    - name: django_secret_key
      key: secret/data/nalkinscloud-resume/backend/database
      property: username
    - name: db_pass
      key: secret/data/nalkinscloud-resume/backend/database
      property: password
#
#    - name: email_username
#      key: secret/data/nalkinscloud-resume/backend/database
#      property: username
#    - name: email_password
#      key: secret/data/nalkinscloud-resume/backend/database
#      property: password
#
#    - name: google_oauth_client_id
#      key: secret/data/nalkinscloud-resume/backend/database
#      property: username
#    - name: google_oauth_client_secret
#      key: secret/data/nalkinscloud-resume/backend/database
#      property: password
#    - name: github_oauth_client_id
#      key: secret/data/nalkinscloud-resume/backend/database
#      property: username
#    - name: github_oauth_client_secret
#      key: secret/data/nalkinscloud-resume/backend/database
#      property: password