{{- $fullName := include "nalkinscloud.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.docker.dockerSecretName }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
type: Opaque
data:
  django_secret_key: {{ .Values.secrets.django_secret_key | default (randAlphaNum 50) | b64enc | quote }}
  db_user: {{ .Values.secrets.database.username | b64enc | quote }}
  db_pass: {{ .Values.secrets.database.password | b64enc | quote }}
  email_username: {{ .Values.secrets.email.username | b64enc | quote }}
  email_password: {{ .Values.secrets.email.password | b64enc | quote }}
