{{ if .Values.image.imagePullSecret }}
{{- $fullName := include "mosquitto.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: private-docker-repo
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{ end }}