apiVersion: v2
appVersion: 0.1.19
description: Nalkinscloud IOT mqtt simulator
icon: null
maintainers:
- email: levinsonarie@gmail.com
  name: Arie Lev
  url: https://www.nalkins.cloud
name: nalkinscloud-mqtt-simulators
sources:
- https://github.com/ArieLevs/NalkinsCloud
version: 0.1.9
