# Default values for nalkinscloud-mqtt-simulators.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: docker.nalkins.cloud/nalkinscloud-mqtt-automation-simulators/nalkinscloud-mqtt-automation-simulators
  tag: 0.1.21
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

podAnnotations:
  vault.hashicorp.com/log-level: "debug"
  ## Annotations docs here: https://www.vaultproject.io/docs/platform/k8s/injector/annotations/
  vault.hashicorp.com/agent-inject: "false"
  vault.hashicorp.com/agent-inject-status: "update"
  vault.hashicorp.com/role: "nalkinscloud-mqtt-simulators"
  vault.hashicorp.com/agent-inject-secret-dht-password: "secret/data/nalkinscloud-simulators/devices/dht"
  vault.hashicorp.com/agent-inject-secret-switch-password: "secret/data/nalkinscloud-simulators/devices/switch"

  ## This should map to the same unique value provided in vault.hashicorp.com/agent-inject-secret-X
  ## Deployment template example can be found here:
  ## https://www.vaultproject.io/docs/platform/k8s/injector/examples/#deployments-statefulsets-etc
  vault.hashicorp.com/agent-inject-template-dht-password: |
    {{- with secret "secret/data/nalkinscloud-simulators/devices/dht" -}}
    dht_pass: {{ .Data.data.password }}
    {{- end -}}
  vault.hashicorp.com/agent-inject-template-switch-password: |
    {{- with secret "secret/data/nalkinscloud-simulators/devices/switch" -}}
    switch_pass: {{ .Data.data.password }}
    {{- end -}}

dependantContainers:
  ## Specify dependant container here as example below
  - name: init-mqtt-broker
    image: busybox
    command: ['sh', '-c', 'until nc -z ${broker_host} ${broker_port} ; do echo waiting for mosquitto; sleep 2; done;']
    env:
      - name: broker_host
        value: "thingsboard-mqtt-transport.thingsboard.svc.cluster.local"
      - name: broker_port
        value: "1883"

envVars:
  environment: alpha
  broker_host: thingsboard.nalkins.cloud
  broker_port: 1883
  broker_tls: false
  broker_tls_skip: true
  dht_user: test_dht_simulator
  dht_qos: 1
  switch_user: test_switch_simulator
  switch_qos: 1

serverCrt: |-
# Mosquitto CRT file content goes here

secrets:
  docker:
    privateRepo: true
    ## if true credentials will be fetched from vault, local registry/username/password ignored
    vaultSecret: true
    registry: docker.nalkins.cloud
    username: username
    password: passowrd
  devices:
    ## if true credentials will be fetched from vault, local password ignored, else from external secrets
    vaultSecret: false

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
