{{ $labels := include "external-secrets-crd.labels" . }}
{{- range $key, $value := .Values.externalSecrets }}
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: {{ $value.name }}
  labels:
    {{- $labels | nindent 4 }}
  {{- with $value.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $value.specs }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
---
{{- end }}