{{- range $key, $value := .Values.secrets }}
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: {{ $value.name }}
  {{- with $value.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with $value.specs }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}