# Default values for envoy-grpc-test.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

server:
  replicaCount: 1
  image:
    repository: docker.io/arielev/grpc-messenger
    imagePullPolicy: Always
  podSecurityContext: {}
  # fsGroup: 2000

  service:
    type: ClusterIP
    port: 50505

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

client:
  replicaCount: 1
  image:
    repository: docker.io/arielev/grpc-messenger
    imagePullPolicy: Always
  podSecurityContext: {}
  securityContext: {}

nameOverride: ""
fullnameOverride: ""
