{{- $fullName := include "nalkinscloud-mqtt-simulators.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "nalkinscloud-mqtt-simulators.name" . }}
    helm.sh/chart: {{ include "nalkinscloud-mqtt-simulators.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nalkinscloud-mqtt-simulators.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "nalkinscloud-mqtt-simulators.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    {{- with .Values.podAnnotations }}
      annotations:
    {{- toYaml . | nindent 8 }}
    {{- end }}
    spec:
      serviceAccountName: nalkinscloud-mqtt-simulators
      initContainers:
        - name: init-mosquitto
          image: busybox
          command: ['sh', '-c', 'until nc -z ${mosquitto_host} ${mosquitto_port} ; do echo waiting for mosquitto; sleep 2; done;']
          env:
            - name: mosquitto_host
              value: "{{ .Values.envVars.broker_host }}"
            - name: mosquitto_port
              value: "{{ .Values.envVars.broker_port }}"
    {{- with .Values.additionalInitContainers }}
        {{- toYaml . | nindent 8 }}
    {{- end }}

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.serverCrt }}
          volumeMounts:
            - name: mosquitto-server-crt
              mountPath: /src/certificates/mosquitto_server.crt
              subPath: mosquitto_server.crt
              readOnly: true
          {{- end }}

          {{- if not .Values.secrets.devices.vaultSecret }}
          envFrom:
            - secretRef:
                name: {{ $fullName }}-devices
          {{- end }}

          env:
            - name: version
              value: {{ .Values.image.tag | quote }}

            {{- range $key, $value := .Values.envVars }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}

            {{- if .Values.graylog.graylog_enabled -}}
            {{- range $key, $value := .Values.graylog }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: mosquitto-server-crt
          configMap:
            name: {{ $fullName }}
      {{- if .Values.secrets.docker.privateRepo }}
      imagePullSecrets:
        - name: {{ $fullName }}-registry-secret
      {{- end -}}
