{{- $fullName := include "nalkinscloud-mqtt-simulators.fullname" . -}}
{{- if .Values.secrets.docker.privateRepo }}
apiVersion: v1
kind: Secret
metadata:
  name: private-image-pull-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
type: Opaque
data:
  dhtPass: {{ .Values.secrets.devices.dht_pass | b64enc | quote }}
  switchPass: {{ .Values.secrets.devices.switch_pass | b64enc | quote }}
