{{- $fullName := include "nalkinscloud-mqtt-simulators.fullname" . -}}
{{- if .Values.secrets.docker.privateRepo }}
  {{- if .Values.secrets.docker.vaultSecret }}
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: {{ $fullName }}-registry-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  backendType: vault
  vaultRole: kubernetes-external-secrets
  kvVersion: 2
  template:
    type: kubernetes.io/dockerconfigjson
  data:
    - name: .dockerconfigjson
      key: secret/data/nexus/docker
      property: dockerconfigjson
  {{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-registry-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
  {{- end }}
{{ end }}
---
{{- if not .Values.secrets.devices.vaultSecret }}
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: {{ $fullName }}-devices
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  backendType: vault
  vaultRole: kubernetes-external-secrets
  kvVersion: 2
  data:
    - name: dht_pass
      key: secret/data/nalkinscloud-simulators/devices/dht
      property: password
    - name: switch_pass
      key: secret/data/nalkinscloud-simulators/devices/switch
      property: password
{{- end }}